language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - Gemfile
  - gemfiles/activesupport-5.0.gemfile
  - gemfiles/activesupport-5.1.gemfile
before_script:
  - gem update --system
